language: objective-c
osx_image: xcode8.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Stage1st.xcworkspace
  - IOS_SCHEME="Stage1st"
  - IOS_SDK=iphonesimulator
  matrix:
    - DESTINATION="OS=10.1,name=iPhone 7 Plus"     SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
before_install:
#  - gem uninstall cocoapods --all --executables
#  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod env 
  - pod repo update --silent
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Application in Debug and Run Tests if specified
#  - if [ $RUN_TESTS == "YES" ]; then
#      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
#    else
#      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
#    fi

  # Build Application in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
notifications:
  email: false
  slack: ainocrop:HkpADe4Z7ArRMAkoD75IBfv2
